apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc
  namespace: pihole-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-storage
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pihole-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pihole-storage
  resources:
    requests:
      storage: 1Gi
